#!/bin/bash

set -e


echo $CHE_POSTGRES_USERNAME $CHE_POSTGRES_PASSWORD $CHE_POSTGRES_DATABASE

psql <<-EOSQL
    CREATE ROLE $CHE_POSTGRES_USERNAME superuser;
    CREATE USER $CHE_POSTGRES_USERNAME WITH PASSWORD '$CHE_POSTGRES_PASSWORD';
    ALTER ROLE $CHE_POSTGRES_USERNAME superuser;
    ALTER USER $CHE_POSTGRES_USERNAME WITH PASSWORD '$CHE_POSTGRES_PASSWORD';
    CREATE DATABASE $CHE_POSTGRES_DATABASE;
    GRANT ALL PRIVILEGES ON DATABASE $CHE_POSTGRES_DATABASE TO $CHE_POSTGRES_USERNAME;
    ALTER USER $CHE_POSTGRES_USERNAME WITH SUPERUSER;
    ALTER ROLE $CHE_POSTGRES_USERNAME WITH LOGIN;
EOSQL

echo $POSTGRESQL_USER $POSTGRESQL_USER $POSTGRESQL_USER $POSTGRESQL_DATABASE

#psql  <<-EOSQL
#    CREATE ROLE $POSTGRESQL_USER superuser;
#    CREATE USER $POSTGRESQL_USER WITH PASSWORD '$POSTGRESQL_PASSWORD';
#    CREATE DATABASE $POSTGRESQL_DATABASE;
#    GRANT ALL PRIVILEGES ON DATABASE $POSTGRESQL_DATABASE TO $POSTGRESQL_USER;
#    ALTER USER $POSTGRESQL_USER WITH SUPERUSER;
#    ALTER ROLE $POSTGRESQL_USER WITH LOGIN;
#EOSQL


#pg_ctl -w stop

unset CHE_POSTGRES_DATABASE
unset CHE_POSTGRES_USERNAME
unset CHE_POSTGRES_PASSWORD

#exit 0
